language: python

python:
  - "3.5"

install:
  - pip install travis-sphinx sphinx-rtd-theme jupyter
  - make -C test install VIRTUAL_ENV_OPTS=--system-site-packages

script:
  - make test
  - make documentation
