language: python

python:
  - "3.5"

install:
  - pip install travis-sphinx
  - pip install -r test/requirements.txt
  - make -C test install VIRTUAL_ENV_OPTS=--system-site-packages DEBUG=1

script:
  - make -C documentation
  - make test DEBUG=1
