addons:
  apt_packages:
    - pandoc
    - texlive 
    - texlive-lang-german
    - texlive-latex-recommended  
    - texlive-latex-extra

language: python

python:
  - "3.5"

install:
  - pip install astropy numpy travis-sphinx sphinx-rtd-theme
  - make -C test install

script:
  - make -C doc clean
  - make documentation
  - make test
