#!/usr/bin/env python2.7
import argparse
import sys

from httm import calibrated_transform_from_file, write_raw_fits

if __name__ == "__main__":

    parser = argparse.ArgumentParser(description='Transform a Calibrated FITS file into a RAW FITS file')

    parser.add_argument('--slices', '-s', dest='slices', action='store', type=int, default=4,
                        help="The number of slices in the Calibrated FITS file")
    parser.add_argument('input', nargs='?', type=argparse.FileType('r'), default=sys.stdin,
                        help="The name of the Calibrated FITS file to use as input (defaults to STDIN)")
    parser.add_argument('output', nargs='?', type=argparse.FileType('w'), default=sys.stdout,
                        help="The name of the RAW FITS file to use as output (defaults to STDOUT)")

    args = parser.parse_args()
    write_raw_fits(args.output, calibrated_transform_from_file(args.input))
