#!/usr/bin/env python2.7
import argparse
import logging
import os

from httm import raw_fits_to_calibrated
from httm.data_structures.raw_converter import raw_converter_parameters, raw_transformation_flags
from httm.system.command_line import add_arguments_from_settings
from httm.transformations.raw_converters_to_calibrated import raw_transformations

log_level = os.getenv('LOG', 'WARNING').upper()
logging.basicConfig(
    format="[%(asctime)s] %(levelname)s [%(name)s.%(funcName)s:%(lineno)d] %(message)s"
    if log_level is "DEBUG" else "%(levelname)s %(message)s",
    datefmt="%H:%M:%S",
    level=getattr(logging, log_level))

if __name__ == "__main__":

    parser = argparse.ArgumentParser(description='Transform a RAW FITS file into a Calibrated FITS file')

    parser.add_argument('input', type=str, help="The name of the RAW FITS file to use as input (defaults to STDIN)")
    parser.add_argument('output', type=str,
                        help="The name of the Calibrated FITS file to use as output (defaults to STDOUT)")

    add_arguments_from_settings(parser, raw_transformation_flags)
    add_arguments_from_settings(parser, raw_transformations)
    add_arguments_from_settings(parser, raw_converter_parameters)

    args = parser.parse_args()
    raw_fits_to_calibrated(args.input, args.output,)
