#!/usr/bin/env python2.7
import argparse
import os
import sys

import logging

from httm import raw_fits_to_calibrated

logging.basicConfig(
    format="[%(asctime)s] %(levelname)s [%(name)s.%(funcName)s:%(lineno)d] %(message)s",
    datefmt="%H:%M:%S",
    level=getattr(logging, os.getenv('LOG', 'WARNING').upper()))

if __name__ == "__main__":

    parser = argparse.ArgumentParser(description='Transform a RAW FITS file into a Calibrated FITS file')

    parser.add_argument('--slices', '-s', dest='slices', action='store', type=int, default=4,
                        help="The number of slices in the RAW FITS file")
    parser.add_argument('input', nargs='?', type=argparse.FileType('r'), default=sys.stdin,
                        help="The name of the RAW FITS file to use as input (defaults to STDIN)")
    parser.add_argument('output', nargs='?', type=argparse.FileType('w'), default=sys.stdout,
                        help="The name of the Calibrated FITS file to use as output (defaults to STDOUT)")

    args = parser.parse_args()
    raw_fits_to_calibrated(args.input, args.output,)
