#!/usr/bin/env python

# Make a test image of four 50 x 50 slices for blooming and undershoot
# This puts 1000000 (implicitly electrons) in pixel [25, 25]. The rest of the image is 100.

import sys

import numpy
from astropy.io import fits

if __name__ == "__main__":
    image_data = numpy.zeros((50, 200)) + 100
    image_data[25, 25] = 1000000
    header = fits.Header()
    header['CCDNUM'] = -1
    fits.writeto(sys.argv[1], image_data, header, clobber=True)
