#!/usr/bin/env python

# Make a pattern noise (or bias frame) image to match the spot50 test image.
# Puts ripples in all pixels, including dark pixels.

import sys
import os

import numpy
from astropy.io import fits

if __name__ == "__main__":
    height = 50 + 30
    width = 50 + 22
    image_data = 2.0*numpy.reshape(numpy.sin(range(height*width)), [height,width])
    header = fits.Header()
    header['CCDNUM'] = -1
    header['CAMNUM'] = -1
    header['N_FRAMES'] = 1
    output_file = sys.argv[1]

    try:
        os.remove(output_file)
    except OSError:
        pass

    fits.writeto(output_file, image_data, header)
