#!/usr/bin/env python

# HTTM: A transformation library for RAW and Electron Flux TESS Images
# Copyright (C) 2016, 2017 John Doty and Matthew Wampler-Doty of Noqsi Aerospace, Ltd.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


# Make a test image of four 50 x 50 slices for blooming and undershoot
# This puts 1000000 (implicitly electrons) in pixel [25, 25]. The rest of the image is 100.

import os
import sys

import numpy
from astropy.io.fits import HDUList, PrimaryHDU, Header

if __name__ == "__main__":
    image_data = numpy.zeros((50, 200)) + 100
    image_data[25, 25] = 1000000
    header = Header()
    header['CCDNUM'] = -100
    header['CAMNUM'] = -100
    header['N_FRAMES'] = 1
    output_file = sys.argv[1]

    try:
        os.remove(output_file)
    except OSError:
        pass

    HDUList(PrimaryHDU(image_data, header=header)).writeto(output_file)
