#!/usr/bin/env python

# HTTM: A transformation library for RAW and Electron Flux TESS Images
# Copyright (C) 2016, 2017 John Doty and Matthew Wampler-Doty of Noqsi Aerospace, Ltd.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


from numpy import savez, sin, reshape
import sys

if __name__ == "__main__":
    # Create default pattern noise file

    # Used to generate the file `default_pattern_noise.npz`

    amplitude_electrons = 10

    # noinspection PyTypeChecker
    noise_pattern = reshape(amplitude_electrons * sin(range(2078 * 2136)), (2078, 2136))

    savez(sys.argv[1], pattern_noise=noise_pattern)
