#!/usr/bin/env python
import sys
from numpy import linspace, concatenate, savez, array

if __name__ == "__main__":
    # Create default start of line ringing file

    # This zero-pads the ringing, makes a line for standard TESS format. 
    # Units are electrons, although the linspace approximation came from
    # inspecting an ADU plot of real data.

    video_scale = 5.2
    start_of_line_ringing1 = video_scale * concatenate((linspace(-0.6, 0.4, num=40),
                                                        linspace(0.4, -0.4, 40),
                                                        linspace(-0.4, 0.0, 20),
                                                        linspace(0.0, 0.0, 434)))
    savez(sys.argv[1], start_of_line_ringing=array([start_of_line_ringing1,
                                                    start_of_line_ringing1,
                                                    start_of_line_ringing1,
                                                    start_of_line_ringing1,]))
