#!/usr/bin/env python

# HTTM: A transformation library for RAW and Electron Flux TESS Images
# Copyright (C) 2016, 2017 John Doty and Matthew Wampler-Doty of Noqsi Aerospace, Ltd.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


import sys
from numpy import linspace, concatenate, savez, array


if __name__ == "__main__":
    # Create default start of line ringing file

    # This zero-pads the ringing, makes a line for standard TESS format. 
    # Units are electrons, although the linear space approximation came from
    # inspecting an ADU plot of real data.

    # Used to generate the file `default_start_of_line_ringing.npz`

    video_scale = 5.2
    start_of_line_ringing1 = video_scale * concatenate((linspace(-0.6, 0.4, num=40),
                                                        linspace(0.4, -0.4, 40),
                                                        linspace(-0.4, 0.0, 20),
                                                        linspace(0.0, 0.0, 434)))
    savez(sys.argv[1], start_of_line_ringing=array([start_of_line_ringing1,
                                                    start_of_line_ringing1,
                                                    start_of_line_ringing1,
                                                    start_of_line_ringing1, ]))
